apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: kserve-paddleserver
  annotations:
    prometheus.kc.io/port: '8080'
    prometheus.kc.io/scrape: 'false'
spec:
  supportedModelFormats:
    - name: paddle
      version: "2"
      autoSelect: true
  protocolVersions:
    - v1
  containers:
    - name: kserve-container
      image: kserve-paddleserver:replace
      args:
        - --model_name={{.Name}}
        - --model_dir=/mnt/models
        - --http_port=8080
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "1"
          memory: 2Gi
